name: Bug Report
description: Something is not working correctly or is not working at all!
title: "Bug: <Insert Issue Title Here>"
labels: ["bug", "programming"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        **Example:** Bug: derive_vars_dtm() is returning NA values when using preserve argument
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info or to let you know when the bug has been fixed?
      placeholder: email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what were you expecting to happen before the bug?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: session-info
    attributes:
      label: Session Information
      description: Use `sessionInfo()` in the R console to gather all the details of your environment when the bug happened.
      placeholder: Please cut and paste your session info into here.
      value: "Place the console output here"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Reproducible Example
      description: We love code that can reproduce the example. Check out [reprex](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html){target="_blank"}
      placeholder: Tell us what you see!
      value: "Please give us as many details as you can! The faster we can recreate the bug, the faster we can get a fix in the works.  Warning, Error Messages and Screenshots are also great."
    validations:
      required: false

