name: Onboarding Tasks
description: Bringing a Core or non-Core member onto the admiral team
title: "Onboaring:  <Insert Issue Title Here>"
labels: ["onboarding"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Welcome to the Team!  We love contributors!
  - type: checkboxes
    id: core
    attributes:
      label: Onboarding tasks for Core (Roche-GSK) Team Members
      description: 
      options:
        - label: Given a tour of Github from a core member.
        - label: Understand how to do a Create Issues and do a Pull Request
        - label: Understand the Programming Strategy
        - label: Invited to all relevant meeting - Stand Ups, Retrospective, Sprint Planning
        - label: Given access to Box and relevant documents
        - label: Given write access to Github Repository
        - label: Slack channel invites to admiral and admiral_dev
        - label: Introduction to Teams ways of working
        
  - type: checkboxes
    id: non-core
    attributes:
      label: Onboarding tasks for non-Core Team Members
      description: 
      options:
        - label: Given a tour of Github from a core member.
        - label: Understand how to do a Create Issues and do a Pull Request
        - label: Understand the Programming Strategy
        - label: Given access to Box and relevant documents
        - label: Given write access to Github Repository
        - label: Slack channel invites to admiral and admiral_dev










