name: Bug Report
description: File a bug report
title: "Bug: "
labels: ["bug", "programming"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: R Version
      description: Use `R.version` in your console to find the version of R you are using 
      placeholder: 4.1.2
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Reproducible Example
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Please give us as many details as you can!"
    validations:
      required: true

