name: Bug Report
description: Something is not working correctly or is not working at all!
title: "Bug: <Insert Issue Title Here>"
labels: ["bug", "programming"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info or to let you know when the bug has been fixed?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: session-info
    attributes:
      label: Session Information
      description: Use `sessionInfo()` to gather all the details of your environment when the bug happened.
      placeholder: Please cut and paste your session info into here.
      value: "Place here"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Reproducible Example
      description: We love code that can reproduce the example
      placeholder: Tell us what you see!
      value: "Please give us as many details as you can! Error Messages are also great and screenshots"
    validations:
      required: false

