name:  Updates or Enhancements for Documentation
description: Update for Documentation
title: "Documentation Update or Enhancement: "
labels: ["vignettes", "website", "documentation"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        The admiral team loves documentation!  Sometimes it gets out of sync or is not very helpful.  
        Please help us keep the documenation up to date or make suggestions to enhance it.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: docs-out-if-sync
    attributes:
      label: Please fill out if documentation is out of sync or is in need of a refresh?
      description: Screen shots are super helpful here!
      placeholder: Tell us what you see!
      value: "Something is out of sync or needs a refresh"
    validations:
      required: false
  - type: textarea
    id: docs-enhancement
    attributes:
      label: Please fill out if documentation is in need of enhancements?
      description: Be as desciprtive as you can!
      placeholder: The more detail the more likely we can act on it.
      value: "I have an idea for some enhancements!"
    validations:
      required: false