name: Feature Request
description: Enchancement to admiral functionality
title: "Feature Request: "
labels: ["enhancement", "programming"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to ask for a new feature!  We are excited!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Your Feature Update?
      description: Tell us what you think should be new in admiral in as few words as possible.
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: What do you expect to see?
      description: Please 
      placeholder: 
      required: true
  - type: textarea
    id: logs
    attributes:
      label: What do you expect to see?
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
       placeholder: 
  