name: Onboarding Tasks
description: Brining a Core or non-Core member onto the admiral team
title: "Onboaring: "
labels: ["onboarding"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Welcome to the Team!  We love contributors!
  - type: checkboxes
    id: core
    attributes:
      label: Onboarding tasks for Core Team Members
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
        - label:  e to follow this project's Code of Conduct
        - label:  to follow this project's Code of Conduct
        - label: I   to follow this project's Code of Conduct
          required: true











