name: Tester Feedback
description: Are you testing admiral! You are amazing!
title: "Tester Feedback"
labels: ["tester feedback"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Many thanks for testing out admiral!  
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: Please select a category this issue is focused on?
      multiple: true
      options:
        - Function
        - Documentation
        - New Feature
        - General
  - type: textarea
    id: what-happened
    attributes:
      label: Let's get specific on your category on function and documentation
      description: Which function, documentation needs some sprucing up?
      placeholder: Tell us what you see!
      value: "Something"
    validations:
      required: false
  - type: textarea
    id: what 
    attributes:
      label: Let's get specific on your category on New Feature or General
      description: Which function, documentation or s
      placeholder: Tell us what you see b!
      value: "Something a"
    validations:
      required: false
  